### ISSUE TITLE
Retry is never set to true for workers

### ISSUE THREAD

**Issue by hphilipps** [RichardKnop/machinery#113]
There is support for relaunching failed workers with a backoff time in machinery, but in the Redis and AMQP brokers the `retry` field is never set to true, so workers will never be restarted when they fail. As the Redis worker will die as soon as Redis becomes unavailable, setting `retry` to true would prevent the worker from staying down forever in such a case. Is there a reason for not retrying?

**Comment by RichardKnop** [comment]
I just looked at the code and it seems retry is set to `true` in the AMQP broker constructor:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go#L28

You can test this by launching example worker:

```sh
go run examples/worker/worker.go 
```

And then turning RabbitMQ off and on:

```sh
launchctl stop homebrew.mxcl.rabbitmq
launchctl start homebrew.mxcl.rabbitmq

# wait a bit to test the retry fibonacci sequence will be reset to 1 after reconnection

launchctl stop homebrew.mxcl.rabbitmq
launchctl start homebrew.mxcl.rabbitmq
```

There does not seem to be a way to turn off the retry logic, it's just hardcoded to `true`.

However I just looked in the redis broker and it seems that retry is always `false` there as in the constructor it's not set:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L35

So a quick fix would be to set retry to `true` in `NewRedisBroker` function.

This could possibly be made configurable. Although I don't think anybody would ever want to disable the connection retrying (as your workers would die in case of network problem in your infrastructure which is bad). So perhaps we should just make sure it is hardcoded to `true` also in the Redis broker.

Thoughts?

I have mostly used machinery with RabbitMQ broker so that one is probably best tested. Redis was added based on the interface I came up with for AMQP but it is less tested so there might be small issues like this.

**Comment by RichardKnop** [comment]
Sorry for this issue. For quick fix I suggest, just set retry to `true` in `NewRedisBroker`:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L35

That should prevent worker from quitting if there is problem with Redis connection.

Do you want to create a PR for this?

**Comment by hphilipps** [comment]
Ah - I didn't notice that retry is already set to true for AMQP. In this case I will just create a small PR to also set it to true for Redis - because that's what I'm mostly using. I think there is no reason to disable retries at all. The fibonacci based backoff sequence is nice and should be used! 😄

**Comment by RichardKnop** [comment]
Sure, submit PR and I will merge it.
