### ISSUE TITLE
Recommended procedure to start the worker(s) under development and production?

### ISSUE THREAD

**Issue by kartlee** [RichardKnop/machinery#121]
Is there a recommended notes to restart the workers under development and production environment? I see an equivalent for celery and it would be useful to have one for the machinery project.

-Karthik

**Comment by saggit** [comment]
Have same question, For now, If I press control +C, the worker stop immediately, How to implement a feature like celery, give it a warm shutdown?

**Comment by kartlee** [comment]
Any update?

**Comment by RichardKnop** [comment]
I agree this is an issue. I don't have much free time at the moment so I would accept PRs dealing with this problem.

**Comment by foobargeez** [comment]
In need of warm shutdown akin to Celery.  @RichardKnop, I would be happy to contribute but I am not currently a golang guy, unfortunately.  BTW, I know time is the issue here but if it helps, I am happy to swallow some of the development costs if you are willing to put in hours.  If you're interested, please drop me a message in gitter.  Thanks!
