### ISSUE TITLE
Performance issue using redis as backend

### ISSUE THREAD

**Issue by vanng822** [RichardKnop/machinery#140]
I use this package for running some background tasks and just upgraded to the latest (for using ETA and Group) but it turned out that the CPU usage was really high, almost 50% for go process and 40% for redis server (Redis server v=3.2.4  MAC).

I tried to profiling CPU but not really figured out what was going on. Any one has experienced or has time to test it out and confirm?

I use Mac and run go version go1.8.1, Redis server v=3.2.4, github.com/robfig/cron for generating tasks. Web output of Profiling https://gist.github.com/vanng822/427b4a49952cc4f754d94bc5094ea3e5

**Comment by RichardKnop** [comment]
@vanng822 I have pushed a small improvement so try rebasing from master.

I have added a timer to only ping idle Redis connections every 15 seconds instead of every time you get a connection from pool:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L403

And I have also added a small delay to the go routine which is looking for delayed tasks in a `ZSET` as otherwise it would keep running `ZRANGEBYSCORE` relentlessly.

I am not sure if these changes help but give it a try.

I might spend some time this weekend to do some profiling to see what is causing high CPU usage. You can take a look at Redis broker and backend files in case you seem some obvious problem there which could be causing this:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go
https://github.com/RichardKnop/machinery/blob/master/v1/backends/redis.go

**Comment by vanng822** [comment]
Thank for quick response

Not really help
Look like that 
`"ZRANGEBYSCORE" "delayed_tasks" "0" "1495105325993073062" "LIMIT" "0" "1"`
returns zero length items wish causing error, the timer you just put in never reach.

Not really sure why it is empty now and not on the old version (revision bae667d798a33928db0349a5e2d098d20ce3b301). Maybe something that you know by heart? need to set it up?

Another question is that is it sufficient to run a timer there? The CPU is actually reduce a lot if we put in a timer.

**Comment by RichardKnop** [comment]
OK. I have moved the timer up. Try it now.

The older revision did not have goroutine which runs `ZRANGEBYSCORE`. This is needed for delayed tasks. So might be the culprit. I think this issue might be solved by placing a timer/delay to a proper place.

**Comment by vanng822** [comment]
That helps thank you,

I was thinking that delayed_tasks is nil when there are no delayed tasks. Isn't it better to stay in that for loop since it is expected that len(items) == 0, just continue instead of returning an error.
