### ISSUE TITLE
`Connection Reset By Peer` When sending lots of tasks by `SendGroup`

### ISSUE THREAD

**Issue by Jolly23** [RichardKnop/machinery#144]
I use `SendGroup` to send my tasks, when I send 10 tasks, it works well. However, if I send 100 tasks, it tells me `read tcp 127.0.0.1:56064->127.0.0.1:56379: read: connection reset by peer. `Therefore, they won't be execute.
I do not know how to solve this problem.

**Comment by Jolly23** [comment]
Sometimes, my project has to send tens of thousands of I/O tasks
It used celery with rabbitMQ before I decided to shift the language from python to Golang
I am searching for the Golang RabbitMQ plan, I think using this package is the best way to replace the python's method.
But I meet this problem, I hope someone could help me.

**Comment by Jolly23** [comment]
I tried to use `SendTask` with a loop to send big amount of tasks, but it is very slow. 
So I have to use the `SendGroup`

**Comment by RichardKnop** [comment]
@Jolly23 I am aware of this problem but am currently very busy to really look into it.

What broker and backend are you using? I don't recommend RabbitMQ as backend if you want to process large amount of tasks. I would recommend RabbbitMQ for broker and Redis for backend in that case.

Or perhaps you can even try using Redis/Redis broker/backend combination to see if it is faster.

The code which sends a group of tasks is defined here: https://github.com/RichardKnop/machinery/blob/master/v1/server.go#L177

Do you see any obvious problem with it?

What I thing the problem is: https://github.com/RichardKnop/machinery/blob/master/v1/common/amqp.go

The way I use `amqp` package it keeps opening new connection all the time. 

Where as with `redis` package I use connection pooling as you can see here: https://github.com/RichardKnop/machinery/blob/master/v1/common/redis.go

So I think what we need to do is implement connection pooling for AMQP so we reuse connection instead of opening new connection all the time because in your case it will try to open 100-200 connections to RabbitMQ at once with current implementation.

If you want to contribute and implement connection pooling this would be a good place to start: https://github.com/RichardKnop/machinery/blob/master/v1/common/amqp.go

**Comment by RichardKnop** [comment]
@Jolly23 You can see here:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L367
https://github.com/RichardKnop/machinery/blob/master/v1/backends/redis.go#L317

That with redis it is using a connection pool. So it keeps reusing same connections.

But with AMQP, this:

https://github.com/RichardKnop/machinery/blob/master/v1/backends/amqp.go#L49
https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go#L33

and all other places in AMQP broker and backed files where it calls `b.Open` or `b.Connect` it opens a new connection which does not scale.

In theory all you would need to do would be to edit a single file:

https://github.com/RichardKnop/machinery/blob/master/v1/common/amqp.go

And implement some sort of simple connection pooling there so it keeps a pool of connection and reuses them. So that might be the way to solve this problem for you.

I would start with refactoring this method:

https://github.com/RichardKnop/machinery/blob/master/v1/common/amqp.go#L96

If you can make that method use a connection pool instead opening a new connection all the time it might help solve your problem or at least make performance much better.

**Comment by RichardKnop** [comment]
@asimashfaq FYI

**Comment by Jolly23** [comment]
Thank you, now, I knew the problem.
Thanks again for your serious and responsible.
I will try to shift the backend.

**Comment by Jolly23** [comment]
But I just found that I met this problem when using RabbitMQ for broker and redis for backend, as you said.

**Comment by RichardKnop** [comment]
@Jolly23 I did a quick test with 100 tasks and I am not getting an error. Replace `example/machinery.go` with this file: https://gist.github.com/RichardKnop/985d00eda8375aa4596c9d545b32538d

And try to run:

```sh
go run example/machinery.go worker
```

And:

```sh
go run example/machinery.go send
```

I haven't had time to do any more detailed testing but this quick test processes group of 100 tasks and I don't get the error you are getting. Hmm.
