### ISSUE TITLE
Workers getting tasks from multiple queues

### ISSUE THREAD

**Issue by WillAbides** [RichardKnop/machinery#209]
I'm on a project using the redis broker with consumers who need to get tasks from multiple queues, and it would be great if we could have only one BLPOP per consumer instead of one per queue per consumer.

From what I can tell, this will require significant changes to RedisBroker and Worker or a creating a new broker and taskprocessor.

I have a few questions before I start working on this.
1. Am I missing an obvious way to do this with the current code?
2. Would you consider merging a PR with this functionality?
3. Would you consider a PR that allows custom brokers?
4. Do you think we would be better off modifying RedisBroker and Worker or creating a new broker and taskprocessor?

From what I've seen, I really like machinery, and I would like to do this work in a way that can contribute back and avoid maintaining a fork.

**Comment by RichardKnop** [comment]
Hi,

Currently with Redis, you are correct it's not possible. Each worker will only consume via `BLPOP` from one queue.

Take a look at `fanout` exchange type for AMQP. It doesn't do exactly what you want (have one worker consume messages from multiple queues) but depending on your use case it might be a possible solution. 

I think it's more natural to do it this way, instead of having one worker accept tasks from multiple queues, send a message that needs to be processed in a different way (e.g. new order message might need to trigger fulfillment process, sending of order confirmation email, record order for reporting etc).

The problem with having workers accept tasks from multiple queues is I have no idea at the moment how to implement it in a way which is not super convoluted. The code would get quite messy as I would suddenly need to manage multiple connections to consume tasks.

To answer your questions:

  1. There is no way to do that currently.
  2. I would consider it but:
    a) It would need to be implemented for both AMQP and Redis as I don't want to have uniform behaviour for all supported brokers.
    b) It would need to be reasonably well done so the code is readable and possible to maintain.
  3. Again I would consider it but I would have to see it. It's difficult for me to imagine right now how it would work. It should be possible to implement your own broker by implementing this interface: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/interfaces.go#L9 Not sure how it is possible to allow custom brokers brokers in any more "dynamic" way as Go is statically typed language. I have been playing around with plugins in order to allow dynamic registering of tasks to workers via shared objects (`*.so` files). Plugins only work on Linux though currently afaik so I am a bit reluctant to start relying on them.
  4. Please explain how you would modify the Redis broker (e.g. what Redis commands would you use instead of `BLPOP`, or would you run multiple BLPOPs in goroutines to fetch messages from multiple queues?).

**Comment by WillAbides** [comment]
Thanks for taking the time to provide detailed answers to all my questions.

> Take a look at fanout exchange type for AMQP

Unless I am misunderstanding fanout, I don't think it will work for us because we need each task to be processed by exactly one worker. Also, adding RabbitMQ to the stack could be a tough sell. Not that there's anything wrong with RabbitMQ. There's just a lot of effort involved in supporting a new service.

> I would consider it but:
a) It would need to be implemented for both AMQP and Redis 

This will be challenging for me because I haven't worked with AMQP before. I would need to partner with somebody for that portion.

> b) It would need to be reasonably well done so the code is readable and possible to maintain.

Of course all my code is perfectly readable and maintainable. ;-) Some local preschools even read it aloud at story time.

>  It should be possible to implement your own broker by implementing this interface: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/interfaces.go#L9

Thanks for pointing this out. This should be all I need on that front.

> Please explain how you would modify the Redis broker (e.g. what Redis commands would you use instead of BLPOP

I would use a single BLPOP with multiple keys.  `nextTask` might end up looking something like this:
```golang
func (b *RedisBroker) nextTask(queues ...string) (result []byte, err error) {
...
	blpopArgs := make([]interface{}, len(queues) + 1)
	for i, q := range queues {
		blpopArgs[i] = q
	}
	blpopArgs[len(queues)] = 1
	items, err := redis.ByteSlices(conn.Do("BLPOP", blpopArgs...))
...
}
```
`nextDelayedTask` would be trickier because ZRANGEBYSCORE doesn't accept multiple keys like BLPOP does.  That would make it O(n) for the number of queues the worker is watching. That could possibly be mitigated by having one goroutine watch the delayed queues on behalf of all workers and forward new jobs to whichever worker has been waiting longest.  Another option would be a goroutine that regularly checks delayed queues and moves tasks to the regular queue when their time comes.

However, my current project doesn't have a need for delayed tasks, so I wouldn't implement it in a custom broker unless I intend for it to be merged upstream.

**Comment by WillAbides** [comment]
We ended up changing the design of the project that was going to require this change.  Instead we are using machinery in a more conventional way.

Before the design change, I did start on a broker that would allow a worker to work multiple queues.  As @RichardKnop said, I was able to implement `brokers.Interface` to create a custom broker in my own package.  I couldn't use `machinery.NewServer` with my custom broker because `BrokerFactory` doesn't know about it, but that wouldn't have been necessary anyway.
