### ISSUE TITLE
Redis broker fails when redis url contains a user name in addition to a password

### ISSUE THREAD

**Issue by joelpresence** [RichardKnop/machinery#214]
Thanks for making this library available - I really like it and enjoy using it.  :-)

Your factory doesn't seem to properly parse redis urls like `redis://user:password@host:port`.

Many common Redis cloud providers, e.g RedisCloud on Heroku, provider redis urls like the following `redis://user:password@host:port`.  This is a valid URL and also a valid Redis url as per [the IANA scheme for redis](https://www.iana.org/assignments/uri-schemes/prov/redis).  However, machinery doesn't handle such urls properly and seems to use `user:password` as the password when attempting to connect instead of just `password`.  Neither Redis nor RedisCloud themselves seem to need or check the `user` portion when connecting, but they do accept it as part of the URL.  So does `github.com/garyburd/redigo/redis`, the go redis library that you're using.

We can't start mangling with our REDISCLOUD_URL on Heroku since that could change at any time.  I'd propose adapting your `ParseRedisURL` to properly parse urls with `user:password` but then just throw away the `user` portion.  Alternatively, you could use `redis.DialURL` and pass the url as-is without parsing it yourself, but just handling the user in the parse is the least impactful change to the codebase I think.

Would you be open to a PR to fix this?  :-)

**Comment by joelpresence** [comment]
Actually, I don't even think `redis://password@host:port` is a legal URL is it?  I think the spec requires the user info to either be `user` or `user:password`, but just `password` is not legal because it's ambiguous - does the plain text value without a colon represent a password or a user.

**Comment by RichardKnop** [comment]
@joelpresence You are basically correct. The reason why Redis broker URL format is expected to be:

```
redis://[password@]host[port][/db_num]
redis+socket://[password@]/path/to/file.sock[:/db_num]
```

... is because Redis does not have a concept of users (e.g. there is no access control). So `user:password` didn't make sense to me as there is no such thing as username in case of Redis. When choosing format for Redis URL I was following format of AMQP which was the first implemented broker but I leaved out username part for the above reason.

All you can do is use a basic authentication mechanism to protect Redis instance with a password but you can't create user spaces such as you'd be able to do when working with MySQL database, for example.

See here: https://redis.io/topics/security

I'm open to PRs to fix this so URL in format `redis://user:password@host:port` will be accepted (the user bit would be ignored, no matter what value there is.).

I think that's the most sensible way to do this.

**Comment by migmartri** [comment]
Redis since 6.0 has in fact the [notion of user](https://redis.io/commands/auth). Would it make sense to add support to it?

Thanks!
