### ISSUE TITLE
support customized result backend

### ISSUE THREAD

**Issue by balzaczyy** [RichardKnop/machinery#28]
The latest server.go changes the following error handling.

	backend, err := BackendFactory(cnf)
	if err != nil {
		return nil, err
	}

It used to be:

	// Backend is optional so we ignore the error
	backend, _ := BackendFactory(cnf)

This change breaks my customised result backend. I still want to monitor the error returned by NewServer(). Can you revert it or provide an alternative to support customised result backend?

**Comment by RichardKnop** [comment]
This was related to another issue: https://github.com/RichardKnop/machinery/issues/27

I chose to make result backend mandatory for now as otherwise it was easy to get errors and the documentation was a bit misleading so I fixed that too. Perhaps I should revisit that decision.

I will be travelling this weekend so I might not be able to look at this until next week.

**Comment by RichardKnop** [comment]
@balzaczyy Is your backend too customised? Ot do you think it is generic enough you could contribute it via a pull request? If it's not too specific to your use case, it can be added as another backend option.

**Comment by RichardKnop** [comment]
@balzaczyy git pull

It should allow custom backends again. Sorry.

**Comment by balzaczyy** [comment]
Cool. Thanks. I'm using ElasticSearch as the result backend. But it's only partially implemented for my own purpose. I will try create a pull request when I finish the remaining function.
