### ISSUE TITLE
SQS broker will process the old tasks that failed before

### ISSUE THREAD

**Issue by tailingchen** [RichardKnop/machinery#291]
In aws_sqs.go, the worker does not delete the message if failed to process it and the message will be delivered again after VisibilityTimeout.
https://github.com/RichardKnop/machinery/blob/master/v1/brokers/aws_sqs.go#L221

On the other hand, if I use the retry mechanism, worker will send another retry task to sqs queue. 
https://github.com/RichardKnop/machinery/blob/master/v1/worker.go#L170

According to the above, there are two same tasks in sqs queue.

What can I do if I don't want the duplicate tasks in queue?

IMHO, the sqs broker should delete the message after processing it no matter if it is handled successfully or not.

**Comment by RichardKnop** [comment]
@tailingchen Yes I think this is a bug. In the AMQP reference broker, it asks message off the queue after processing whether there was error or not. See here:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go#L237-L239

Then taskRetry can republish task to the queue again to be retried if the task is configured for retry attempts.

**Comment by RichardKnop** [comment]
AMQP should be used as a reference broker, it was developed first and other brokers should follow it's steps as closely as possible.

For Redis, it is simpler, because Redis queues are not very sophisticated. There is no concept of ack/nack when consuming messages

So there's no need to do anything after processing: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L305

Because BLPOP removes task from Redis queue immediately, no need to ack/nack: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L313

**Comment by tailingchen** [comment]
@RichardKnop My bad. The original logic is right! I think I have misunderstood on this. 

If the task need to retry, the worker will re-send the task and return nil error if re-sending task successfully, then the old task will be deleted. Otherwise, the old task will be kept in SQS if failed to re-send task.
https://github.com/RichardKnop/machinery/blob/master/v1/worker.go#L189
