### ISSUE TITLE
amqp high cpu usage

### ISSUE THREAD

**Issue by wizard580** [RichardKnop/machinery#35]
when I start server and there no workers with registered tasks which server sends, there many queries to amqp and near 100% cpu usage

**Comment by RichardKnop** [comment]
I think this is caused by: https://github.com/RichardKnop/machinery/blob/master/v1/backends/result.go#L71

Basically, if you call AsyncResult.Get method, it uses loop to check if the task has completed.

You can avoid this by not using blocking AsyncResult.Get (which is there mostly for convenience and testing/debugging) calls and just design your tasks to be completely asynchronous using callbacks.

It is similar to Python's Celery framework where the blocking get methods are implemented for convenience but should not be used in real applications, they rather recommend to just trigger asynchronous tasks and not wait for a result.

For example, if you need to do something with a result from task A, set success callback of the A task to B, which will do your business logic with values returned by B. And just trigger A without waiting for the result.

Not sure there is a more efficient way to optimise AsyncResult.Get. Any suggestions?

**Comment by wizard580** [comment]
There not all clear with callbacks.
Can you show example with explanations?
And sure it's good to update docs.
