### ISSUE TITLE
A broker written with Go channels

### ISSUE THREAD

**Issue by parhamdoustdar** [RichardKnop/machinery#63]
I was thinking of having a broker written entirely in Go. Its benefits would be:

- No external dependencies: you don't need Redis or AMPQ. It's all Go.
- You're not limited to marshalable data: I have to do some weird things because I can't pass a channel to my task handler function. If this was all in Go, I could pass any value I wanted.

Would it work with Machinery? Would there be a point in it? I was thinking that it would reduce a lot of boilerplate code in projects which want to do some asynchronous jobs such as sending emails, without depending on a messaging queue, or people like me, who want to pass in unmarshalable values to their functions.

**Comment by RichardKnop** [comment]
@parhamdoustdar Sure.

But if you are going to use just pure Go then there is no need for machinery at all.

The advantage of something like RabbitMQ or Redis is you can have workers running on multiple servers and distribute your tasks to be processed on many machines. This makes horizontal scaling easier.

You can also make your architecture more decoupled and run different tasks on different servers configured specifically for such job.

The problem is, if you want to pass messages describing tasks between different servers, you have to do it in some common format and JSON is probably the best one for that.

I'm not sure there would be a point in doing this as you could just implement something for you in pure Go and not use this library at all if it is an overkill and you don't need it.

**Comment by parhamdoustdar** [comment]
> The advantage of something like RabbitMQ or Redis is you can have workers running on multiple servers and distribute your tasks to be processed on many machines. This makes horizontal scaling easier.

Very true. My use case is to only use Machinery so that I wouldn't have to implement my own library for queues and workers in Go, and that's why I use Machinery. I hadn't considered what you are saying though. Thanks for enlightening me.
