### ISSUE TITLE
Support unix domain socket Redis connections

### ISSUE THREAD

**Issue by hryx** [RichardKnop/machinery#89]
Hello,

I'm working on an application which uses Machinery with a Redis backend, both embedded on a single desktop client. For a few reasons, we've concluded that using a unix domain socket is preferable to a network socket. Socket connections are already supported in redigo, so I'd like to propose extending that support to Machinery.

This may not fit perfectly with the current means of instantiating a backend/broker, but here are some thoughts:

- Add support for `redis.DialOption`s in `RedisBackend` or in the `NewRedisBackend` constructor. This would be the most open-ended and probably best way of customizing use of Redis, since it lets the user granularly set a password, database number, and connection options.
- The existing `ParseRedisURL` function wouldn't work well with file paths — currently it assumes that what comes after the final `/` is a DB number — so maybe a separate URL scheme would be needed. E.g.:
```
"redissocket:///path/to/file.sock"
"redissocket:///path/to/file.sock:/db" -- use ":" to separate final segment
```
In either case, the user should be able to supply `redis.DialOption`s to modify options even if the URL scheme can't.

I'd love to hear your thoughts on this proposal and am willing to work on a pull request if there is a design proposal that you find acceptable. Let me know what you think and how I can help!

**Comment by RichardKnop** [comment]
I like this proposal. I had the similar problem before when adding support for Redis passwords, to support both:

- `redis://127.0.0.1:6379`
- `redis://password@127.0.0.1:6379`

I was thinking at a time to possibly change `Config. Broker ` and `Config.ResultBackend` from strings to some sort of a struct with multiple properties instead of supporting ever more complex connection URL formats.

Perhaps like this:

```go
type Connection struct {
  Host string `yaml:"host"`
  Socket string `yaml:"socket"`
  Port string `yaml:"host"`
  Username string `yaml:"username"`
  Password `yaml:"password"`
  Cursor `yaml:"cursor"` // perhaps rename this to DB?
}

type Config struct {
  Broker          Connection `yaml:"broker"`
  ResultBackend   Connection `yaml:"result_backend"`
  ResultsExpireIn int    `yaml:"results_expire_in"`
  Exchange        string `yaml:"exchange"`
  ExchangeType    string `yaml:"exchange_type"`
  DefaultQueue    string `yaml:"default_queue"`
  BindingKey      string `yaml:"binding_key"`
}
```

This would probably mean more refactoring but it would be much more flexible approach as it is generic enough to support different broker / backends without having to parse X connection URL formats.

I would prefer that instead of making `ParseRedisURL` more complex.

If you think that's too much work, we could do something like:

- `redis://password@host:port/db`
- `redissocket://password@/path/to/file.soc:port/db`

So first split by `@`, then by `:`, then by `/`. Could work for all cases.

**Comment by hryx** [comment]
Ah, modifying `Config` looks like a more accessible and sensible approach than the `redis.DialOption` suggestion I made. I like it better.

I wouldn't mind making the changes, but the downside is that it would break existing configs and necessitate a `v2` API. This change alone seems a little small to warrant a whole new API version.

Expanding the URL parser is a bit of a cheap workaround, but it would be quicker and shouldn't necessitate a new API version. How about I do that for now, and the config change can go on a v2 wishlist?

**Comment by RichardKnop** [comment]
Tbh, I think this library is still quite new / experimental so I hope most people are pinning down against a specific commit in their projects and not just pulling from master (in case there are some breaking changes).

But I agree, the second option seems quicker and won't break anything for now.

I might do the config modification later, it would still be under v1, not sure I want to move to v2 unless there will be some serious changes to the library.

**Comment by hryx** [comment]
Roger that. Thanks @RichardKnop, I'll get started on updating this and send a PR soon.

**Comment by RichardKnop** [comment]
Sounds good!
