### ISSUE TITLE
extensible brokers and backend?

### ISSUE THREAD

**Issue by palanglung** [RichardKnop/machinery#97]
current implementation for broker and backend are with factory that use connection prefix as backend selector and i think is not posible to extend the broker or backend? CMIIW how about
database/sql style backends and brokers?

**Comment by RichardKnop** [comment]
@palanglung To implement a new broker or backend, you just need to follow these interfaces:

- https://github.com/RichardKnop/machinery/blob/master/v1/brokers/interfaces.go
- https://github.com/RichardKnop/machinery/blob/master/v1/backends/interfaces.go

The current factory is not very flexible, I agree. That is one of the things I would like to refactor.

Instead of prefixes I would like to instead make config object more robust so you can define connection details there without custom connection string formats.

**Comment by mdouchement** [comment]
I have made a prototype with Postgres [here](https://github.com/mdouchement/machinery-pg) that works well.

The relevant points are:
- As @RichardKnop said, its a bit difficult to use external implementation with the current factory
- SQL databases do not fit well for tasks' broker because you need to poll the data

**Comment by RichardKnop** [comment]
@mdouchement If you'd like to improve / refactor to make it easier to add custom external implementations, PRs welcome :)
